// File: MP3.h. Used in Can2Cluster.ino project.
// Purpose: MP3 Player Defines
// Author: T. Black
// Created: Jan-07-2019
// Last Change: Feb-20-2019
/*
   GNU GENERAL PUBLIC LICENSE VERSION 3
   Copyright (C) 2019  T. Black
   This file is part of Can2Cluster_Ford.ino (hereby referred to as Can2Cluster).
   
   Can2Cluster is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Can2Cluster is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Can2Cluster.  If not, see <https://www.gnu.org/licenses/>.
*/

//
// Voice Announce Files created by OpenTxSpeaker, http://www.open-tx.org/2014/03/15/opentx-speaker
// MP3 Wave Audio Files generated by Audacity V2.1.2. 
// Audacity Effect: Normalize: -6.0dB (voices files only)
// Audacity Export Type: Other uncompressed files, signed 16-bit PCM

// SD Card MP3 Folder, File Numbers:
#define MP3_FILE_STOP    1                              // File 0001.mp3, Announce "ENGINE OFF"
#define MP3_FILE_FIX     2                              // File 0002.mp3, Announce "3500 RPM AT 60MPH"
#define MP3_FILE_GTEST   3                              // File 0003.mp3, Announce "GAUGE SWEEP TEST"
#define MP3_FILE_PRESET1 4                              // File 0004.mp3, Announce "GAUGE PRESET #1"
#define MP3_FILE_PRESET2 5                              // File 0005.mp3, Announce "GAUGE PRESET #2"
#define MP3_FILE_HELLO   6                              // File 0006.mp3, Announce "WELCOME ..."
#define MP3_FILE_REV1    7                              // File 0007.mp3, Engine Rev #1 Sound, approx 23 secs.
#define MP3_FILE_DRIVE   8                              // File 0008.mp3, Car Drive Sounds, approx 36 secs.
#define MP3_FILE_REV2    9                              // File 0009.mp3, Engine Rev #2 Sound, approx 9 secs.
#define MP3_FILE_LOBEEP  10                             // File 0010.mp3, Low Pitch Beep Sound, 250mS duration.
#define MP3_FILE_HIBEEP  11                             // File 0011.mp3, High Pitch Beep Sound, 250mS duration.
#define MP3_FILE_BLOOP   12                             // File 0012.mp3, Bloop Beep Sound, 205mS duration.
#define MP3_FILE_HORN    13                             // File 0013.mp3, Horn Sound, 380mS duration.
#define MP3_FILE_TURNON1 14                             // File 0014.mp3, Announce "PLEASE TURN ON CLUSTER"
#define MP3_FILE_TURNON2 15                             // File 0015.mp3, Announce "PLEASE TURN ON NIGHT TIME LIGHTS"
#define MP3_FILE_DAYON   16                             // File 0016.mp3, Announce "DAY TIME LIGHTS ON"
#define MP3_FILE_NIGHTON 17                             // File 0017.mp3, Announce "NIGHT TIME LIGHTS ON"
#define MP3_FILE_SHUTDN  18                             // File 0018.mp3, Announce "SHUTTING DOWN, GOODBYE"

// SD Card /ADVERT Folder, File Numbers:
#define MP3_FILE_AD_LOBEEP 1                            // Ad File 0001.mp3, Low Pitch Beep Sound, 250mS duration.
#define MP3_FILE_AD_HIBEEP 2                            // Ad File 0002.mp3, High Pitch beep Sound, 250mS duration.
#define MP3_FILE_AD_BLOOP  3                            // Ad File 0003.mp3, Bloop beep Sound, 205mS duration.
#define MP3_FILE_AD_HORN   4                            // Ad File 0004.mp3, Horn Sound, 380mS duration.

// Sequencer Pause Times for Barge-in (Advertise mode) Sound effects:
#define MP3_PAUSE_HORN   385                            // Horn sound duration (+overhead), in mS.
#define MP3_PAUSE_BLOOP  225                            // Bloop Beep sound duration (+overhead), in mS.
#define MP3_PAUSE_LOBEEP 255                            // Low Pitch Beep sound duration (+overhead), in mS.
#define MP3_PAUSE_HIBEEP 255                            // High Pitch Beep sound duration (+overhead), in mS.