// File: Sequencer.h. Used in Can2Cluster.ino project.
// Purpose: Animation Sequencer Structures and Data.
// Author: T. Black
// Created: Jan-07-2019
// Last Change: Feb-20-2019
/*
   GNU GENERAL PUBLIC LICENSE VERSION 3
   Copyright (C) 2019  T. Black
   This file is part of Can2Cluster_Ford.ino (hereby referred to as Can2Cluster).
   
   Can2Cluster is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Can2Cluster is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Can2Cluster.  If not, see <https://www.gnu.org/licenses/>.
*/

//
// ============================================================================================================================

#define SEQ_DATA_CNT    6                               // Number of Data Columns in a Sequencer Array Map's Row.
#define SEQUENCE_DLY    100                             // Delay time between Animation steps, in mS.
#define SEQ_DRV_STEPS   ((sizeof(SequencerDrive))/sizeof(SequencerDrive[0]))
#define SEQ_FIXED_STEPS ((sizeof(SequencerFixed))/sizeof(SequencerFixed[0]))
#define SEQ_REV1_STEPS  ((sizeof(SequencerRev1))/sizeof(SequencerRev1[0]))
#define SEQ_REV2_STEPS  ((sizeof(SequencerRev2))/sizeof(SequencerRev2[0]))
#define SEQ_STOP_STEPS  ((sizeof(SequencerStop))/sizeof(SequencerStop[0]))
#define SEQ_TEST_STEPS  ((sizeof(SequencerTest))/sizeof(SequencerTest[0]))
#define SEQ_USER1_STEPS ((sizeof(SequencerUser1))/sizeof(SequencerTest[0]))
#define SEQ_USER2_STEPS ((sizeof(SequencerUser2))/sizeof(SequencerTest[0]))

// ============================================================================================================================
//       DATA ARRAY MAP FORMATTING NOTES
// Data order is <SPEED>, <RPM/100>, <COOLANT TEMPERATURE>, <OIL PRESSURE>, <CHARGE INDICATOR>
// SPEED      = 0-120 (MPH)
// RPM        = 0-70 (0-7000)
// TEMPERATURE= COLD_TEMP, COOL_TEMP, LOW_TEMP, MID_TEMP, WARM_TEMP, HIGH_TEMP, OVER_TEMP
// OIL PRESS  = OIL_OFF, OIL_ON
// CHARGE IND = CHARGE_OFF, CHARGE_ON
// BRAKE IND  = BRAKE_OFF, BRAKE_ON
// ============================================================================================================================
//           USER DEFINED PRE-SETS
// Feel free to configure these to your preferred gauge configuration. Multiple data rows allowed (to create animation).
// Sequences start with BRAKE_OFF, followed by BRAKE_ON. This is used to initialize the brake indicator.
// User Pre-Set #1 Sequence Array Map.
//  {SPD-RPMX100-TEMP-OILPRS--CHARGE---BRAKE----}
const byte PROGMEM SequencerUser1[][SEQ_DATA_CNT] = {
    {0,0,OVER_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {0,0,OVER_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    {0,0,OVER_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120,70,OVER_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
};

// User Pre-Set #2 Sequence Array Map.
//  SPD-RPMX100-TEMP-OILPRS--CHARGE---BRAKE----
const byte PROGMEM SequencerUser2[][SEQ_DATA_CNT] = {
    {0,0,HIGH_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {0,0,HIGH_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    {0,0,HIGH_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {20,10,HIGH_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF}
};

// ============================================================================================================================
//          ANIMATION SEQUENCER MAPS (Data rows are executed at 100mS intervals)

// Long Playing Engine Rev #1 Animation Sequence Array Map.
// This animation uses MP3 File MP3_FILE_REV1
//  SPD-RPMX100-TEMP-OILPRS--CHARGE---BRAKE----
const byte PROGMEM SequencerRev1[][SEQ_DATA_CNT] = {
    { 0, 0,COOL_TEMP,OIL_OFF,CHARGE_ON,BRAKE_ON},       // TIME 0S
    { 0, 0,COOL_TEMP,OIL_OFF,CHARGE_ON,BRAKE_ON},
    { 0, 0,COOL_TEMP,OIL_OFF,CHARGE_ON,BRAKE_ON},
    { 0, 0,COOL_TEMP,OIL_OFF,CHARGE_ON,BRAKE_ON},
    { 0, 0,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 1S
    { 0, 7,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 2S
    { 0, 5,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0,40,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 3S
    { 0,40,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,40,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,40,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,40,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,40,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,20,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,15,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 7,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // TIME 4S
    { 0,45,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,42,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,46,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,48,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,45,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,48,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,42,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,30,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,20,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0,10,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // TIME 5S
    { 0, 9,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 8,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 42,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 40,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0,38,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // TIME 6S
    { 0,30,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,15,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,12,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,12,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,38,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,38,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,36,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,37,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0,38,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 7S
    { 0,20,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,18,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,15,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,12,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 8,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 8,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 6,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 8S
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,30,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,30,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,25,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,20,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,18,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0,15,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 9S
    { 0,10,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 9,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 8,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 8,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,38,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,36,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,34,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,35,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,36,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0,30,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 10S
    { 0,27,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,23,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,20,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,15,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,12,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 9,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 6,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 11S
    { 0, 7,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,47,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,45,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,40,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,25,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,20,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0,15,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 12S
    { 0,12,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 9,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,46,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,45,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,44,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,46,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,45,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,44,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,46,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0,40,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 13S
    { 0,37,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,34,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,30,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,27,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,52,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,52,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,45,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,47,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,50,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0,40,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 14S
    { 0,35,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,30,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,20,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,55,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,53,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,55,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,53,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,51,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0,40,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 15S
    { 0,37,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,34,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,30,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,25,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,22,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,52,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,52,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0,48,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 16S
    { 0,40,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,35,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,20,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,15,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,9,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,9,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,8,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 17S
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 9,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,11,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 9,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,11,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,9,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0, 9,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 18S
    { 0, 9,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,11,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 8,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 19S
    { 0, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 20S
    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,42,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,41,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,42,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,40,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,35,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,25,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,20,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,15,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0,12,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 21S
    { 0,45,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,41,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,40,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,32,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,30,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,25,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,20,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 22S
    { 0,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 9,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 9,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 8,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 23S
    { 0, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},         // Time 23S
    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,MED_TEMP,OIL_OFF,CHARGE_ON,BRAKE_ON}
    
};


// Short Playing Engine Rev #2 Animation Sequence Array Map.
// This animation uses MP3 File MP3_FILE_REV2
//  SPD-RPMX100-TEMP-OILPRS--CHARGE---BRAKE----
const byte PROGMEM SequencerRev2[][SEQ_DATA_CNT] = {
    { 0, 0,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 0S
    { 0, 4,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 1S
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,45,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,42,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,40,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,42,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,35,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,30,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0,25,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 2S
    { 0,20,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,15,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,50,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,52,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,45,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,45,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,48,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,45,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,47,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0,35,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // Time 3S
    { 0,35,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,32,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,25,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,25,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,20,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,20,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,15,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0,10,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 8,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
   
    { 0, 8,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // Time 4S
    { 0, 7,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // Time 5S
    { 0, 4,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // Time 6S
    { 0, 4,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // Time 7S
    { 0, 4,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // Time 8S
    { 0, 4,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0, 5,WARM_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // Time 9S
    { 0, 4,WARM_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 3,WARM_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 2,WARM_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 1,WARM_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COOL_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COOL_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COOL_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COOL_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COOL_TEMP,OIL_OFF,CHARGE_ON,BRAKE_ON}   
};
 
 
// Car Driving Animation Sequence Array Map.
// This animation uses MP3 File MP3_FILE_DRIVE
//  SPD-RPMX100-TEMP-OILPRS--CHARGE---BRAKE----
const byte PROGMEM SequencerDrive[][SEQ_DATA_CNT] = {
    { 0, 0,LOW_TEMP,OIL_OFF,CHARGE_ON,BRAKE_ON},        // TIME 0S
    { 0, 0,LOW_TEMP,OIL_OFF,CHARGE_ON,BRAKE_ON},
    { 0, 1,LOW_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 2,LOW_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 3,LOW_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_ON},
    { 0, 3,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 7,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 8,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 6,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // TIME 1S
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // TIME 2S
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},        // TIME 3S
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 6,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 4S
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 5S
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 6S
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 7S
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,LOW_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 8S
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 9S
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 10S
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 11S
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 12S
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 2, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 13S
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    
    { 2, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // TIME 14S
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 2, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},

    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // Time 15S
    { 3, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 3, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 3, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 4, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 4, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 5, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 5, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 5, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 16S
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 17S
    { 5, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 5, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 18S
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 5, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 2, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 3, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 19S
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 5, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 5, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 20S
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 3, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 6, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 7, 8,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 7, 9,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 21S
    { 8,11,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 9,13,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {10,15,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {13,17,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {15,20,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {17,22,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {19,23,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {21,24,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {23,25,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {25,26,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 22S
    {27,27,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {29,28,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {30,29,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {31,30,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {32,31,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {33,32,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {34,33,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {35,34,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {36,35,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    
    {37,36,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 23S
    {38,37,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {39,38,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {40,39,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {41,40,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {42,35,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {43,33,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {44,30,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {45,31,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {46,32,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {47,33,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 24S
    {48,34,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {49,35,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {50,36,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {51,37,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {52,38,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {53,39,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {54,40,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {55,41,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {56,42,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {57,43,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 25S
    {58,44,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {59,45,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {60,46,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {61,47,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {62,48,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {63,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {64,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {65,51,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {66,52,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {67,52,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 26S
    {68,53,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {69,54,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {70,55,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {71,56,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {72,56,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {73,55,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {74,54,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {75,53,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {76,52,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {77,51,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 27S
    {78,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {79,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {80,48,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {81,47,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {82,46,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {83,46,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {84,45,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {85,45,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {86,44,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {87,44,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 28S
    {88,44,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {89,45,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {90,46,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {91,47,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {92,48,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {93,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {94,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {95,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {96,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {96,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 29S
    {96,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {96,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {96,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {96,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {96,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {96,51,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {96,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {97,51,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {97,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {98,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 30S
    {98,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {99,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {99,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {100,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {100,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {98,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {97,50,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {96,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {95,49,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {94,48,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 31S
    {93,48,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {92,47,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {91,47,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {90,46,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {90,46,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {90,45,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {91,45,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {92,44,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {92,43,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {92,42,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 32S
    {91,41,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {91,40,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {91,39,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {91,38,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {90,37,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {90,36,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {90,35,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {90,34,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {88,33,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {88,32,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 33S
    {87,32,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {87,32,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {87,31,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {86,31,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {86,31,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {86,30,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {85,30,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {85,29,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {85,29,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    
    {84,28,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 34S
    {83,28,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {82,27,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {80,27,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {78,26,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {74,26,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {70,25,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {66,25,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {62,24,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {58,24,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    
    {54,22,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 35S
    {50,20,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {46,18,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {42,16,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {38,14,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {34,12,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {30,10,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {26, 9,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {22, 8,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {18, 7,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {14, 6,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},       // Time 36S
    {10, 5,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 8, 4,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 6, 3,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 4, 2,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 2, 1,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 1, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,MED_TEMP,OIL_OFF,CHARGE_ON,BRAKE_ON},

 };



// Gauge Sweep Test Animation Sequence Array Map.
// This anmimation uses file MP3_FILE_GTEST.
//  SPD-RPMX100-TEMP-OILPRS--CHARGE---BRAKE----
const byte PROGMEM SequencerTest[][SEQ_DATA_CNT] = {
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // Time 0S
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},      // Time 1S
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},      // Time 2S
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},      // Time 3S
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},      // Time 4S
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},


    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},      // Time 5S
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},     // Time 6S
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},      // Time 7S
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},     // Time 8S
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},      // Time 9S
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},      // Time 10S
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},     // Time 11S
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},      // Time 12S
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0,70,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},     // Time 13S
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {120, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 0, 0,COLD_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},     // Time 14S
    { 0, 0,COLD_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},     // Time 15S
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},

    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},      // Time 16S
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},     // Time 17S
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},

    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},     // Time 18S
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},     // Time 19S
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},

    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},     // Time 20S
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},

    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},     // Time 21S, Force a warning beep to mark end of test.
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
   
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},     // Time 22S, Force a warning beep to mark end of test.
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},

    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},     // Time 23S, Force a warning beep to mark end of test.
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 5, 5,HIGH_TEMP,OIL_OFF,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,MED_TEMP,OIL_OFF,CHARGE_ON,BRAKE_ON}
    };


// Engine Stopped Animation Sequence Array Map.
// Does not use a MP3 file.
//  SPD-RPMX100-TEMP-OILPRS--CHARGE---BRAKE----
const byte PROGMEM SequencerStop[][SEQ_DATA_CNT] = {
    { 0, 0,LOW_TEMP,OIL_OFF,CHARGE_ON,BRAKE_OFF},
    { 0, 0,LOW_TEMP,OIL_OFF,CHARGE_ON,BRAKE_OFF},
    { 0, 0,LOW_TEMP,OIL_OFF,CHARGE_ON,BRAKE_OFF},
    { 0, 0,LOW_TEMP,OIL_OFF,CHARGE_ON,BRAKE_OFF},
    { 0, 0,LOW_TEMP,OIL_OFF,CHARGE_ON,BRAKE_OFF},
    { 0, 0,LOW_TEMP,OIL_OFF,CHARGE_ON,BRAKE_OFF},
    { 0, 0,LOW_TEMP,OIL_OFF,CHARGE_ON,BRAKE_ON}
};

// Fixed Speed/RPM Animation Sequence Array Map.
// Zero Gauge then Set to 60mph, 3500RPM
// This anmimation uses file MP3_FILE_FIX.
//  SPD-RPMX100-TEMP-OILPRS--CHARGE---BRAKE----
const byte PROGMEM SequencerFixed[][SEQ_DATA_CNT] = {
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},       // Time 0S
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_ON},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 0, 0,COLD_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    { 5, 3,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {10, 6,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {15, 9,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    
    {20,12,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},      // Time 1S
    {25,15,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {30,18,COOL_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {35,21,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {40,24,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {45,27,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {50,30,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {55,33,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF},
    {60,35,MED_TEMP,OIL_ON,CHARGE_OFF,BRAKE_OFF}

};


